# Generated by Django 5.2.17 on 2026-08-10 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("current_location", models.CharField(max_length=200)),
                ("pickup_location", models.CharField(max_length=200)),
                ("dropoff_location", models.CharField(max_length=200)),
                ("cycle_used_hours", models.FloatField()),
                ("start_datetime", models.DateTimeField()),
                ("result", models.JSONField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
